[platformio]
default_envs = zepto_blink
src_dir = .

[env]
platform = ./platforms/zepto-mspm0
board = zeptomspm0l1117
framework = baremetal
upload_protocol = custom
build_flags =
  -ffreestanding
  -fdata-sections
  -ffunction-sections
  -Wall
  -Wextra
  -DZEPTO_I2C_ECHO_ADDR=0x33
  -DZEPTO_CPU_HZ=32000000UL
build_src_filter =
  -<*>
  +<src/*.c>
  +<examples/baremetal/blink/src/*.c>
upload_command = ${PROJECT_DIR}/scripts/flash_zepto_bsl.sh ${PROJECT_DIR}/.pio/build/${PIOENV}/firmware.bin

[env:zepto_blink]
build_flags =
  ${env.build_flags}
  -DZEPTO_APP_BLINK=1
